on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make the file
      run: make -C ./inluppar/inlupp4 all
    - name: run unit tests for AST
      run: make -C ./inluppar/inlupp4 UnitTest_ast
    - name: run integration tests for AST
      run: make -C ./inluppar/inlupp4 IntegrationTest_ast
    - name: run integration and unit tests for parser
      run: make -C ./inluppar/inlupp4 ParserTests
    - name: run integration tests for calculator
      run: make -C ./inluppar/inlupp4 CalculatorTests
