on:
  push:
    branches:
    - master
    
jobs:
  run_tests:
    name: run the tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make the file
      run: make -C ./inluppar/inlupp4 all
    - name: run tests
      run: make -C ./inluppar/inlupp4 test
      
